const START_GAME = 'GAME_START';
const CELL_SELECTED = 'CELL_SELECTED';
const WORD_SUBMIT = 'WORD_SUBMIT';
const STOP_GAME = 'STOP_GAME';

export {
    START_GAME,
    CELL_SELECTED,
    WORD_SUBMIT,
    STOP_GAME
}